name: JWT App CI/CD

on:
  push:
    branches: [main]

env:
  NODE_VERSION: 18
  PORT: 4000
  STAGING_URL: https://web-lab5-staging.onrender.com
  RENDER_STAGING_HOOK: https://api.render.com/deploy/srv-d54vkjq4d50c739kfbcg?key=A3GO59A5CW0

jobs:
  # =========================
  # CI: Build + Unit + Integration Tests
  # =========================
  test:
    name: üß™ Unit & Integration Tests
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s --health-timeout=5s --health-retries=5
    env:
      MONGO_URI: mongodb://127.0.0.1:27017/web_lab5
      MONGO_URI_TEST: mongodb://127.0.0.1:27017/web_lab5_test
    steps:
      - uses: actions/checkout@v4
      - name: üü¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: üì¶ Install dependencies
        run: npm ci
      - name: üß™ Run unit tests
        run: npm run test:unit
      - name: üß™ Run integration tests
        run: npm run test:integration

  # =========================
  # STAGING deploy + E2E
  # =========================
  staging:
    name: üöÄ Deploy Staging + E2E
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: üöÄ Trigger Render Staging Deployment
        run: |
          echo "Calling Render webhook..."
          curl -s -X POST ${{ env.RENDER_STAGING_HOOK }}

        - name: ‚è≥ Wait until staging is up
        run: |
          echo "Waiting a few seconds for staging deployment to start..."
          sleep 20  # –ø–∞—É–∑–∞ –ø–µ—Ä–µ–¥ —Ü–∏–∫–ª–æ–º, —á—Ç–æ–±—ã –Ω–µ –¥–µ—Ä–≥–∞—Ç—å —Å—Ç–∞—Ä—ã–π –¥–µ–ø–ª–æ–π
          echo "Checking staging health..."
          n=0
          until curl -s -f ${{ env.STAGING_URL }}/health > /dev/null 2>&1 || [ $n -ge 30 ]; do
            sleep 10              n=$((n+1))
            echo "Waiting... ($n)"
          done
        
          if [ $n -ge 30 ]; then
            echo "Staging did not become ready in time"
            exit 1
          fi
         echo "Staging is up!"
        

          - name: üîß Fix jest permissions
          run: chmod +x ./node_modules/.bin/jest
        
          - name: üß™ Run E2E tests on staging
          env:
            BASE_URL: ${{ env.STAGING_URL }}
          run: npm run test:e2e
        

  # =========================
  # PRODUCTION (–∑–∞–≥–ª—É—à–∫–∞)
  # =========================
  production:
    name: üöÄ Deploy Production
    runs-on: ubuntu-latest
    needs: staging
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: ‚è∏Ô∏è Placeholder for production deployment
        run: echo "Production deploy skipped for now"
